services:
    mongo:
        image: mongo:latest
        environment:
            - MONGODB_DATABASE="chiwawer"
        ports:
            - 27017:27017

    mongo-express:
        image: mongo-express
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo
            - ME_CONFIG_MONGODB_PORT=27017
        depends_on:
            - mongo
        ports:
            - 8081:8081
